export const ERROR_CODES = {
    FULL_SCAN_BLOCKED: 'FULL_SCAN_BLOCKED',
    AGG_TIMEOUT: 'AGG_TIMEOUT',
    COLUMN_METADATA_MISSING: 'COLUMN_METADATA_MISSING',
    VERSION_ERROR: 'VERSION_ERROR',
    ORIGIN_BLOCKED: 'ORIGIN_BLOCKED',
    DATASET_UNCHANGED: 'DATASET_UNCHANGED',
    INDEXEDDB_UNAVAILABLE: 'INDEXEDDB_UNAVAILABLE',
    UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
